baseURL = "https://xiaming.com.cn/"
# title = "夏明"
author = "夏明"
copyright = "Copyright © 2022 夏明 all rights reserved."
paginate = 3
languageCode = "zh"
DefaultContentLanguage = "zh"
enableInlineShortcodes = true
# prevent build failures when using Hugo's Instagram shortcode due to deprecated Instagram API.
# See https://github.com/gohugoio/hugo/issues/7228#issuecomment-714490456
ignoreErrors = ["error-remote-getjson"]

# ------------------------------
theme = "xiamingcomcn"
title = "夏明"

[params]
  twitter = ''
  github = ''
  instagram = ''
# ------------------------------

[menu]

  # [[menu.main]]
    # identifier = "about"
    # name = "关于"
    # url = "/about/"
    # weight = 10

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[privacy]

  [privacy.vimeo]
    disabled = false
    simple = true

  [privacy.twitter]
    disabled = false
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = false
    simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[services]

  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true
